/* eslint-disable import/prefer-default-export */

export const UPDATE_SEARCHED_TAG = 'UPDATE_SEARCHED_TAG';
export const ADD_SEARCHED_TAG = 'ADD_SEARCHED_TAG';
export const UPDATE_SEARCH_BOX_VALUE = 'UPDATE_SEARCH_BOX_VALUE';
export const DELETE_LAST_SEARCHED_TAG = 'DELETE_LAST_SEARCHED_TAG';
export const DELETE_SEARCHED_TAGS = 'DELETE_SEARCHED_TAGS';
